[build-system]
requires = ["uv_build>=0.1.0"]
build-backend = "uv_build"

[project]
name = "oop-arena-batlle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
